# Generated by Django 2.2.10 on 2020-02-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200219_0805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
